### ISSUE TITLE
gz files not processed correctly

### ISSUE THREAD

**Issue by saboswell** [labsyspharm/rnaseq#15]
Jai-Y worked with Nathan and her .gz fastq files would process without unzipping.  Need to update instructions.

**Comment by ArtemSokolov** [comment]
Nathan says that this pertains specifically to the reference files (https://labsyspharm.github.io/rnaseq/refgenome.html), not the input reads FASTQ files.

Looking to see if this is a reproducible issue.

**Comment by smkartik** [comment]
For the moment at least, the reference files need to be unzipped before running bcbio. This may wary between regular RNAseq and DGE. Rory mentioned that he will resolve the issue in a future update

**Comment by ArtemSokolov** [comment]
Just noticed that the exemplar .yaml specifies the unzipped reference. Is the issue just a simple filename mismatch?

In either case, I added the unzip step to instructions in #18.

**Comment by ArtemSokolov** [comment]
Addressed by #18
