### ISSUE TITLE
Create instructions specific to the three main NGS Cores

### ISSUE THREAD

**Issue by saboswell** [labsyspharm/rnaseq#16]
Seems like it might be a good idea to write instructions specific to each core - BPF, Bauer, DFCI - on how to get those FASTQ files properly running through the pipelines.

**Comment by ArtemSokolov** [comment]
@saboswell Is there an exemplar from each core that we can use, so we can see how the data files differ? Ideally, it should be the same cell / experiment type.

**Comment by saboswell** [comment]
Well I think you have data from BPF and I know Kartik has data from Bauer Core.  So those would be good places to start to look at what real data looks like.  Not sure if Nathan has data from DFCI or I could message them to get the details.

**Comment by ArtemSokolov** [comment]
Going to close this one for now. After speaking with Kartik and Nathan, it seems that the instructions can be followed as-is for each of the three cores. Once FASTQ files have been obtained, nothing special is required on a core-by-core basis. There are some potential pre-FASTQ deviations, but that's covered by #17.

We can reopen this later, if something specific comes up. Right now, it's not clear what, if anything, needs to be added.
